# Generated by Django 3.2.8 on 2022-05-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_factura_monto_total'),
        ('plantas', '0002_alter_inventario_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlantasDetalleFacturaFactura', to='factura.factura', verbose_name='Factura'),
        ),
    ]
