# Generated by Django 3.2.8 on 2022-05-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_remove_producto_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
