# Generated by Django 3.2.8 on 2022-05-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0006_producto_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='EstadoDespacho',
        ),
    ]
