# Generated by Django 3.2.8 on 2022-05-27 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_presupuesto'),
        ('plantas', '0007_auto_20220526_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto'),
        ),
        migrations.CreateModel(
            name='IngresoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Venta')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio Compra')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasPlantasUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasPlantasCreateUser', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasPlantasNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasProducto', to='plantas.producto', verbose_name='Producto')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasMedidas', to='plantas.medidas', verbose_name='Medida')),
            ],
            options={
                'verbose_name': 'Ingreso de Compras',
                'verbose_name_plural': 'Ingreso de Compras',
                'ordering': ['-id'],
            },
        ),
    ]
