# Generated by Django 3.2.8 on 2022-06-04 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20220603_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('finalizar_conversacion', models.BooleanField(default=False)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoMensajeUser', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
                ('negocio_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoMensajeDestinoNegocio', to='registration.negocio', verbose_name='Negocio Destino')),
                ('negocio_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoMensajeOrigenNegocio', to='registration.negocio', verbose_name='Negocio Origen')),
            ],
            options={
                'verbose_name': 'Encabezado de Mensaje',
                'verbose_name_plural': 'Encabezado de Mensajes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HiloMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('mensaje_leido', models.BooleanField(default=False, verbose_name='Mensaje Leído')),
                ('encabezado_mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relHiloMensajeEncabezadoMensaje', to='mensajeria.encabezadomensaje', verbose_name='Encabezado')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relHiloMensajejeUser', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
            ],
            options={
                'verbose_name': 'Hilo de Mensaje',
                'verbose_name_plural': 'Hilo de Mensajes',
                'ordering': ['-id'],
            },
        ),
    ]
