# Generated by Django 3.2.8 on 2022-06-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220603_2132'),
        ('mensajeria', '0002_hilomensaje_negocio_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilomensaje',
            name='negocio_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relHiloMensajeNegocioOrigen', to='registration.negocio', verbose_name='Negocio Origen'),
        ),
        migrations.AlterField(
            model_name='hilomensaje',
            name='negocio_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relHiloMensajeNegocioDestino', to='registration.negocio', verbose_name='Negocio Destino'),
        ),
    ]
