# Generated by Django 3.2.8 on 2022-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_auto_20220604_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hilomensaje',
            name='mensaje_leido',
            field=models.BooleanField(default=False, verbose_name='Marcar como Mensaje Leído'),
        ),
    ]
