# Generated by Django 3.2.8 on 2022-05-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220502_1754'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sede',
        ),
        migrations.CreateModel(
            name='SedeCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeClienteCliente', to='clientes.cliente', verbose_name='Cliente')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeClienteSede', to='registration.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Asignar Sede a Cliente',
                'verbose_name_plural': 'Asignar Sede a Cliente',
                'ordering': ['-id'],
                'unique_together': {('sede', 'cliente')},
            },
        ),
    ]
