# Generated by Django 3.2.8 on 2022-05-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefacturaentregables',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de Entregable Facturado', 'verbose_name_plural': 'Detalles de Entregables Facturados'},
        ),
    ]
