# Generated by Django 3.2.8 on 2022-05-19 00:26

import apps.proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20220518_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=apps.proyectos.models.fn_elimina_imagen_cargada),
        ),
        migrations.AlterField(
            model_name='gastosproyecto',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=apps.proyectos.models.fn_elimina_imagen_cargada_gastos),
        ),
    ]
