# Generated by Django 3.2.8 on 2022-05-18 21:55

import apps.ventas_y_alquileres.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0005_alter_factura_monto_total'),
        ('proveedores', '0001_initial'),
        ('registration', '0006_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observacion_entrega', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observación de Entrega')),
                ('observacion_devolucion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observación de Devolución')),
                ('devuelto', models.BooleanField(default=True)),
                ('anotaciones_seguimiento', models.TextField(blank=True, null=True, verbose_name='Anotaciones Seguimiento')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaCreateUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alquiler Máquinas',
                'verbose_name_plural': 'Alquileres de Máquinas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_alquiler', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado del Alquiler')),
            ],
            options={
                'verbose_name': 'Estado Alquiler',
                'verbose_name_plural': 'Estado Alquileres',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Máquina')),
            ],
            options={
                'verbose_name': 'Tipo Máquina',
                'verbose_name_plural': 'Tipos de Máquinas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripció')),
                ('imagen_maquina', models.ImageField(blank=True, null=True, upload_to=apps.ventas_y_alquileres.models.elimina_imagen_cargada)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaCreateUser', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaMarca', to='ventas_y_alquileres.marca', verbose_name='Marca')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaProveedor', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('tipo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relMaquinaTipoMaquina', to='ventas_y_alquileres.tipomaquina', verbose_name='Tipo Máquina')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioMaquinariaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaVentasUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaVentasCreateUser', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaVentasMaquina', to='ventas_y_alquileres.maquina', verbose_name='Máquina')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaVentasNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaVentasTipoMaquina', to='ventas_y_alquileres.tipomaquina', verbose_name='Tipo Máquina')),
            ],
            options={
                'verbose_name': 'Inventario Maquinaria Ventas',
                'verbose_name_plural': 'Inventario Maquinaria Ventas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioMaquinariaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('precio_por_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio por Día')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('disponible', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaAlquilerUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaAlquilerCreateUser', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaAlquilerMaquina', to='ventas_y_alquileres.maquina', verbose_name='Máquina')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioMaquinariaAlquilerNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Inventario Maquinaria Alquiler',
                'verbose_name_plural': 'Inventario Maquinaria Alquileres',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precio')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasCreateUser', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasMaquina', to='ventas_y_alquileres.maquina', verbose_name='Máquina')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relIngresoComprasTipoMaquina', to='ventas_y_alquileres.tipomaquina', verbose_name='Tipo Máquina')),
            ],
            options={
                'verbose_name': 'Inventario Maquinaria Ventas',
                'verbose_name_plural': 'Inventario Maquinaria Ventas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('es_compra', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaVAMaquinariaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaVAMaquinariaCreateUser', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaVAMaquinariaFactura', to='factura.factura', verbose_name='Factura')),
                ('ficha_alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaAlquilerMaquina', to='ventas_y_alquileres.alquilermaquina', verbose_name='Ficha Alquiler')),
                ('maquina_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaInventarioMaquinariaVentas', to='ventas_y_alquileres.inventariomaquinariaventas', verbose_name='Máquina Nueva')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDetalleFacturaVAMaquinariaNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Detalle de Factura V.A. Maquinaria',
                'verbose_name_plural': 'Detalle de Facturas V.A. Maquinaria',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='alquilermaquina',
            name='estado_alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaEstadoAlquiler', to='ventas_y_alquileres.estadoalquiler', verbose_name='Estado del Alquiler'),
        ),
        migrations.AddField(
            model_name='alquilermaquina',
            name='maquina_alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaMaquina', to='ventas_y_alquileres.inventariomaquinariaalquiler', verbose_name='Máquina Alquiler'),
        ),
        migrations.AddField(
            model_name='alquilermaquina',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaNegocio', to='registration.negocio', verbose_name='Negocio'),
        ),
    ]
