# Generated by Django 3.2.8 on 2022-05-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_y_alquileres', '0003_auto_20220523_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquilermaquina',
            name='estado_alquiler',
        ),
    ]
