# Generated by Django 3.2.8 on 2022-05-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_y_alquileres', '0004_remove_alquilermaquina_estado_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquilermaquina',
            name='estado_alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAlquilerMaquinaEstadoAlquiler', to='ventas_y_alquileres.estadoalquiler', verbose_name='Estado del Alquiler'),
        ),
        migrations.AlterField(
            model_name='alquilermaquina',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
