# Generated by Django 3.2.8 on 2022-06-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_actualizado_pro_presupuesto_actualizado_por'),
        ('clientes', '0002_negociocliente_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Empresa')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('atentido', models.BooleanField(default=False, verbose_name='Atendido')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relContactoNegocio', to='registration.negocio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-id'],
            },
        ),
    ]
