# Generated by Django 3.2.8 on 2022-06-03 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20220603_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('primer_nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name='Segundo Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Terminación')),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Salario Base')),
                ('bonificacion_de_ley', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bonificación de Ley')),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Descuentos')),
                ('activo', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEmpleadosUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEmpleadosUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEmpleadosNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Tipo de Puesto',
                'verbose_name_plural': 'Tipos de Puesto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del tipo de pago')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salario Base')),
                ('bonificacion_de_ley', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bonificación de Ley')),
                ('igss', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IGSS')),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Descuentos')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaEmpleados', to='planilla.empleados', verbose_name='Empleado')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaMeses', to='planilla.meses', verbose_name='Planilla del Mes')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaTipoPago', to='planilla.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Planilla Mensual',
                'verbose_name_plural': 'Planillas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosPuesto', to='planilla.puesto', verbose_name='Puesto'),
        ),
    ]
