# Generated by Django 3.2.8 on 2022-06-04 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20220603_2132'),
        ('planilla', '0002_auto_20220604_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planilla',
            options={'ordering': ['id'], 'verbose_name': 'Cuerpo Planilla Mensual', 'verbose_name_plural': 'Cuerpo de Planillas'},
        ),
        migrations.AddField(
            model_name='planilla',
            name='bonos_extra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Bonos Extra'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='bonificacion_de_ley',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Bonificación de Ley'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='descuentos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Descuentos'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='igss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='IGSS'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Salario Base'),
        ),
        migrations.CreateModel(
            name='EncabezadoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('generar_automaticamente', models.BooleanField(default=False)),
                ('ha_sido_generado', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoPlanillaUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoPlanillaUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoPlanillaMeses', to='planilla.meses', verbose_name='EncabezadoPlanilla del Mes')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoPlanillaNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relEncabezadoPlanillaTipoPago', to='planilla.tipopago', verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Encabezado Planilla Mensual',
                'verbose_name_plural': 'Encabezado de Planillas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='planilla',
            name='encabezado_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaEncabezadoPlanilla', to='planilla.encabezadoplanilla', verbose_name='Encabezado de Planilla'),
        ),
    ]
