# Generated by Django 3.2.8 on 2022-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_auto_20220604_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadoplanilla',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
