# Generated by Django 3.2.8 on 2022-05-18 21:55

import apps.transportes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0005_alter_factura_monto_total'),
        ('registration', '0006_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Identificador del GPS')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dispositivo GPS',
                'verbose_name_plural': 'Dispositivos GPS',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('modelo', models.IntegerField(blank=True, null=True, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('cilindraje', models.IntegerField(blank=True, null=True, verbose_name='Cilindraje')),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Chasis')),
                ('tonelaje', models.IntegerField(blank=True, null=True, verbose_name='Tonelaje')),
                ('planca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa')),
                ('disponible', models.BooleanField(default=True)),
                ('permiso_fronterizo', models.BooleanField(default=True)),
                ('baja', models.BooleanField(default=True)),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoPlantaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoPlantaCreateUser', to=settings.AUTH_USER_MODEL)),
                ('dispositivo_gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoDispositivoGPS', to='transportes.dispositivogps', verbose_name='Dispositivo GPS')),
            ],
            options={
                'verbose_name': 'Inventario Vehiculo',
                'verbose_name_plural': 'Inventario Vehiculos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Linea')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_log', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Tipo Log')),
            ],
            options={
                'verbose_name': 'TipoLog',
                'verbose_name_plural': 'Tipos Log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Tipo Vehiculo',
                'verbose_name_plural': 'Tipos Vehiculo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TransmisionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmision_vehiculo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transmisión de Vehículo')),
            ],
            options={
                'verbose_name': 'Transmisión vehículo',
                'verbose_name_plural': 'Transmisión Vehículos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_salida_predio', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida del Predio')),
                ('fecha_entrada_predio', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrada al Predio')),
                ('kilometraje_salida', models.IntegerField(blank=True, null=True, verbose_name='kilometraje Salida')),
                ('kilometraje_entrada', models.IntegerField(blank=True, null=True, verbose_name='kilometraje Entrada')),
                ('kilometros_recorridos', models.IntegerField(blank=True, null=True, verbose_name='kilometros Recorridos')),
                ('direccion_recoleccion', models.TextField(blank=True, null=True, verbose_name='Dirección de Recolección')),
                ('contacto_recoleccion', models.TextField(blank=True, null=True, verbose_name='Contacto Recoleccion')),
                ('fecha_hora_recoleccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Recolección')),
                ('direccion_entrega', models.TextField(blank=True, null=True, verbose_name='Direccion Entrega')),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Entrega')),
                ('contacto_entrega', models.TextField(blank=True, null=True, verbose_name='Contacto Entrega')),
                ('es_nacional', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasCreateUser', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasFactura', to='factura.factura', verbose_name='Factura')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasUser', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRutasInventarioVehiculo', to='transportes.inventariovehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LogVelocidadesGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad_km', models.IntegerField(blank=True, null=True, verbose_name='Velocidad km')),
                ('latitud', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitud')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('dispositivo_gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogVelocidadesGPSDispositivoGPS', to='transportes.dispositivogps', verbose_name='Dispositivo GPS')),
            ],
            options={
                'verbose_name': 'Log Velocidades GPS',
                'verbose_name_plural': 'Log Velocidades GPS',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LogTiemposGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('registro_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora Inicio')),
                ('latitud_inicio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitud Inicio')),
                ('longitud_inicio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitud Inicio')),
                ('registro_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora Fin')),
                ('latitud_fin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitud Fin')),
                ('longitud_fin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitud Fin')),
                ('dispositivo_gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogTiemposGPSDispositivoGPS', to='transportes.dispositivogps', verbose_name='Dispositivo GPS')),
            ],
            options={
                'verbose_name': 'Log Tiempos GPS',
                'verbose_name_plural': 'Log Tiempos GPS',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LogRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_hora_log', models.DateField(blank=True, null=True, verbose_name='Fecha y Hora del Log')),
                ('foto_seguimiento', models.ImageField(blank=True, null=True, upload_to=apps.transportes.models.elimina_imagen_cargada)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogRutaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogRutaCreateUser', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogRutaNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reLogRutaRutas', to='transportes.rutas', verbose_name='Rutas')),
                ('tipo_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relLogRutaTipoLog', to='transportes.tipolog', verbose_name='Tipo de Log')),
            ],
            options={
                'verbose_name': 'Log de Ruta',
                'verbose_name_plural': 'Logs de Rutas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoLinea', to='transportes.linea', verbose_name='Linea'),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoMarca', to='transportes.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoPlantaNegocio', to='registration.negocio', verbose_name='Negocio'),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='tipo_transmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoTransmisionVehiculo', to='transportes.transmisionvehiculo', verbose_name='Tipo Transmisión'),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relInventarioVehiculoTipoVehiculo', to='transportes.tipovehiculo', verbose_name='Tipo Vehículo'),
        ),
        migrations.CreateModel(
            name='FichaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('kilometraje', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kilometraje')),
                ('observacion_llantas', models.TextField(blank=True, null=True, verbose_name='Observación de Llantas')),
                ('observacion_tapiceria', models.TextField(blank=True, null=True, verbose_name='Observación de Tapicería')),
                ('observacion_carroceria', models.TextField(blank=True, null=True, verbose_name='Observación de Carrocería')),
                ('observacion_combustible', models.TextField(blank=True, null=True, verbose_name='Observación de Combustible')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFichaSalidaPilotoUser', to=settings.AUTH_USER_MODEL)),
                ('quien_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFichaSalidaEntregaUser', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reFichaSalidaRutas', to='transportes.rutas', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Ficha de Salida',
                'verbose_name_plural': 'Fichas de Salida',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FichaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('kilometraje', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kilometraje')),
                ('observacion_llantas', models.TextField(blank=True, null=True, verbose_name='Observación de Llantas')),
                ('observacion_tapiceria', models.TextField(blank=True, null=True, verbose_name='Observación de Tapicería')),
                ('observacion_carroceria', models.TextField(blank=True, null=True, verbose_name='Observación de Carrocería')),
                ('observacion_combustible', models.TextField(blank=True, null=True, verbose_name='Observación de Combustible')),
                ('observacion_general', models.TextField(blank=True, null=True, verbose_name='Observación General')),
                ('piloto_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFichaEntradaPilotoUser', to=settings.AUTH_USER_MODEL)),
                ('quien_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFichaEntradaEntregaUser', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reFichaEntradaRutas', to='transportes.rutas', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Ficha de Salida',
                'verbose_name_plural': 'Fichas de Salida',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_autorizacion', models.DateField(blank=True, null=True, verbose_name='Fecha Autorización')),
                ('precio_por_kilometro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio por Kilómetro')),
                ('es_nacional', models.BooleanField(default=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relAsignacionTarifaInventarioVehiculo', to='transportes.inventariovehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Log Tiempos GPS',
                'verbose_name_plural': 'Log Tiempos GPS',
                'ordering': ['-id'],
            },
        ),
    ]
