# Generated by Django 3.2.8 on 2022-05-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariovehiculo',
            old_name='planca',
            new_name='placa',
        ),
    ]
