# Generated by Django 3.2.8 on 2022-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_rename_planca_inventariovehiculo_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaentrada',
            options={'ordering': ['-id'], 'verbose_name': 'Ficha de Entrada', 'verbose_name_plural': 'Fichas de Entrada'},
        ),
        migrations.AlterField(
            model_name='inventariovehiculo',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
