# Generated by Django 3.2.8 on 2022-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_auto_20220522_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logruta',
            name='fecha_hora_log',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del Log'),
        ),
    ]
