# Generated by Django 3.2.8 on 2022-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_alter_logruta_fecha_hora_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='completada',
            field=models.BooleanField(default=True),
        ),
    ]
