# Generated by Django 3.2.8 on 2022-06-03 01:35

import apps.transportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0006_alter_rutas_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariovehiculo',
            name='imagen_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.transportes.models.fn_elimina_imagen_cargada),
        ),
    ]
