# Generated by Django 3.2.8 on 2022-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0007_inventariovehiculo_imagen_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivogps',
            name='velocidad_max_permitida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Velocidad máxima permitida'),
        ),
        migrations.AddField(
            model_name='logvelocidadesgps',
            name='velocidad_alertada',
            field=models.BooleanField(default=False),
        ),
    ]
