# Generated by Django 3.2.8 on 2022-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0008_auto_20220612_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivogps',
            name='velocidad_max_permitida',
            field=models.PositiveIntegerField(blank=True, default=80, null=True, verbose_name='Velocidad máxima permitida'),
        ),
    ]
