# Generated by Django 3.2.8 on 2022-05-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['-id'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['-id'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
