# Generated by Django 3.2.8 on 2022-05-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_negociousuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Tipo de Empleado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Empleado')),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipos de Empleado',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPerfilTipoEmpleado', to='registration.tipoempleado', verbose_name='Tipo de Empleado'),
        ),
    ]
