# Generated by Django 3.2.8 on 2022-05-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220506_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoempleado',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relTipoEmpleadoNegocio', to='registration.negocio', verbose_name='Negocio'),
        ),
    ]
