# Generated by Django 3.2.8 on 2022-05-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_tipoempleado_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('presupuesto_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presepuesto Anual')),
                ('excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Excedente')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('actualizado_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPresupuestoUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPresupuestoUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPresupuestoNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['id'],
            },
        ),
    ]
