# Generated by Django 3.2.8 on 2022-05-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_presupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='actualizado_pro',
            new_name='actualizado_por',
        ),
    ]
