# Generated by Django 3.2.8 on 2022-06-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_actualizado_pro_presupuesto_actualizado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='actualizado_pro',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='salarios',
            name='actualizado_pro',
        ),
        migrations.RemoveField(
            model_name='salarios',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='salarios',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='salarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Meses',
        ),
        migrations.DeleteModel(
            name='Planilla',
        ),
        migrations.DeleteModel(
            name='Salarios',
        ),
        migrations.DeleteModel(
            name='TipoPago',
        ),
    ]
