# Generated by Django 3.2.8 on 2022-05-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_alter_negociousuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gasto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gasto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha de Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Gasto')),
                ('descripcion_gasto', models.TextField(blank=True, null=True, verbose_name='Descripción del Gasto')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistroGastosUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistroGastosUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistroGastosCreateUser', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistroGastosNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relRegistroGastosTipoGasto', to='gastos.tipogasto', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Registro de Gastos',
                'verbose_name_plural': 'Registro de Gastos',
                'ordering': ['-id'],
            },
        ),
    ]
