# Generated by Django 3.2.8 on 2022-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_tipogasto_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrogastos',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Gasto'),
        ),
    ]
