# Generated by Django 3.2.8 on 2022-05-02 01:57

import apps.registration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_depto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='GiroNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_giro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Giro de Negocio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Negocio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.registration.models.elimina_imagen_cargada)),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
                ('activo', models.BooleanField(default=True)),
                ('giro_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPerfilFacultad', to='registration.gironegocio', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_sede', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Sede')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('extension', models.IntegerField(blank=True, null=True, verbose_name='Extensión')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Sede')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeDepartamento', to='registration.departamento', verbose_name='Departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del tipo de pago')),
            ],
        ),
        migrations.CreateModel(
            name='SedeGiroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('preferido', models.BooleanField(default=True)),
                ('giro_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeGiroUsuarioGiroNegocio', to='registration.gironegocio', verbose_name='Giro de Negocio')),
                ('perfil_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeGiroPerfil', to='registration.perfil', verbose_name='Usuario')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeGiroUsuarioSede', to='registration.sede', verbose_name='Sede')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salario Base')),
                ('bonificacion_de_ley', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bonificación de Ley')),
                ('actualizado_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('giro_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosGiroNegocio', to='registration.gironegocio', verbose_name='Giro de Negocio')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosSede', to='registration.sede', verbose_name='Sede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSalariosUser', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salario Base')),
                ('bonificacion_de_ley', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bonificación de Ley')),
                ('igss', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='IGSS')),
                ('actualizado_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaUserActualizadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaUserCreadoPor', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('giro_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaGiroNegocio', to='registration.gironegocio', verbose_name='Giro de Negocio')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaMeses', to='registration.meses', verbose_name='Planilla del Mes')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaSede', to='registration.sede', verbose_name='Sede')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaTipoPago', to='registration.tipopago', verbose_name='Tipo de Pago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPlanillaUser', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPerfilCentroCas', to='registration.sede', verbose_name='Centro CAS'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPerfilUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
