# Generated by Django 3.2.8 on 2022-05-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gironegocio',
            options={'ordering': ['-id'], 'verbose_name': 'Giro de Negocio', 'verbose_name_plural': 'Giros de Negocio'},
        ),
        migrations.AlterModelOptions(
            name='meses',
            options={'ordering': ['id'], 'verbose_name': 'Mes', 'verbose_name_plural': 'Meses'},
        ),
        migrations.AlterModelOptions(
            name='planilla',
            options={'ordering': ['id'], 'verbose_name': 'Planilla', 'verbose_name_plural': 'Planillas'},
        ),
        migrations.AlterModelOptions(
            name='salarios',
            options={'ordering': ['-id'], 'verbose_name': 'Salario', 'verbose_name_plural': 'Salarios'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['-id'], 'verbose_name': 'sede', 'verbose_name_plural': 'sedes'},
        ),
        migrations.AlterModelOptions(
            name='sedegirousuario',
            options={'ordering': ['-id'], 'verbose_name': 'Asignar Sede y Giro', 'verbose_name_plural': 'Asignar Sede y Giro'},
        ),
        migrations.AlterModelOptions(
            name='tipopago',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Pago', 'verbose_name_plural': 'Tipos de Pago'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='giro_negocio',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='giro_negocio',
        ),
        migrations.RemoveField(
            model_name='salarios',
            name='giro_negocio',
        ),
        migrations.AddField(
            model_name='sede',
            name='giro_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relSedeGiroNegocio', to='registration.gironegocio', verbose_name='Giro de Negocio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPerfilCentroCas', to='registration.sede', verbose_name='Sede'),
        ),
        migrations.AlterUniqueTogether(
            name='sedegirousuario',
            unique_together={('sede', 'perfil_usuario')},
        ),
        migrations.RemoveField(
            model_name='sedegirousuario',
            name='giro_negocio',
        ),
    ]
