# Generated by Django 3.2.8 on 2022-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220502_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='bonificacion_de_ley',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Bonificación de Ley'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='igss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='IGSS'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Salario Base'),
        ),
    ]
