# Generated by Django 3.2.8 on 2022-05-04 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_alter_negociousuario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado de Factura')),
            ],
            options={
                'verbose_name': 'Estado de la Factura',
                'verbose_name_plural': 'Estados de la Factura',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_venta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado de la Venta')),
            ],
            options={
                'verbose_name': 'Estado de la Venta',
                'verbose_name_plural': 'Estado de las Ventas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pago', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('numero_factura', models.IntegerField(blank=True, null=True, verbose_name='Número Factura')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de la Factura')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto Facturado')),
                ('completada', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaCliente', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaCreateUser', to=settings.AUTH_USER_MODEL)),
                ('estado_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaEstadoFactura', to='factura.estadofactura', verbose_name='Estado Factura')),
                ('estado_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaEstadoVenta', to='factura.estadoventa', verbose_name='Estado de la Venta')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaTipoPago', to='factura.tipopago', verbose_name='Tipo de Pago')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaUserVendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-id'],
                'unique_together': {('numero_factura', 'negocio')},
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto Venta')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relVentasUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relVentasCreateUser', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relVentasFactura', to='factura.factura', verbose_name='Factura')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relVentasNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-id'],
                'unique_together': {('factura', 'negocio')},
            },
        ),
        migrations.CreateModel(
            name='CorrelativoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('correlativo', models.IntegerField(verbose_name='Correlativo Factura')),
                ('nomenclatura', models.CharField(max_length=15, verbose_name='Nomenclatura Negocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relCorrelativoFacturaNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Correlativo de Factura',
                'verbose_name_plural': 'Correlativos de Facturas',
                'ordering': ['-id'],
                'unique_together': {('correlativo', 'nomenclatura', 'negocio')},
            },
        ),
    ]
