# Generated by Django 3.2.8 on 2022-05-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_negociousuario_options'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado del Pedido')),
            ],
            options={
                'verbose_name': 'Estado del Pedido',
                'verbose_name_plural': 'Estados de los Pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha de Pedido')),
                ('descripcion_detalle_pedido', models.TextField(blank=True, null=True, verbose_name='Descripción del Pedido')),
                ('anotaciones_seguimiento', models.TextField(blank=True, null=True, verbose_name='Anotaciones de Seguimiento')),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPedidoCliente', to='clientes.cliente', verbose_name='Cliente')),
                ('estado_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPedidoEstadoPedido', to='factura.estadopedido', verbose_name='Estado del Pedido')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPedidoNegocio', to='registration.negocio', verbose_name='Negocio')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relPedidoUserVendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relFacturaPedido', to='factura.pedido', verbose_name='Pedido'),
        ),
    ]
