# Generated by Django 3.2.8 on 2022-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20220504_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pedido'),
        ),
    ]
