# Generated by Django 3.2.8 on 2022-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Monto Facturado'),
        ),
    ]
