# Generated by Django 3.2.8 on 2022-05-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_presupuesto'),
        ('factura', '0007_alter_factura_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado del Despacho')),
            ],
            options={
                'verbose_name': 'Estado del Despacho',
                'verbose_name_plural': 'Estados de los Despachos',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='ventas',
            name='monto_venta',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Venta'),
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha del Despacho')),
                ('persona_recibe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona que Recibe')),
                ('anotaciones_despacho', models.TextField(blank=True, null=True, verbose_name='Anotaciones del Despacho')),
                ('completado', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoUpdateUser', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoCreateUser', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoUserEmpleado', to=settings.AUTH_USER_MODEL, verbose_name='Empleado Entrega')),
                ('estado_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoEstadoDespacho', to='factura.estadodespacho', verbose_name='Estado del Despacho')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoFactura', to='factura.factura', verbose_name='Factura')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relDespachoNegocio', to='registration.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-id'],
            },
        ),
    ]
