# Generated by Django 3.2.8 on 2022-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_auto_20220528_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Monto Facturado'),
        ),
    ]
